### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#18]
As a developer I want to run tests, coverage and other pre-commit hooks
So that I can fix any errors before pushing my code to Github

Add precommit hook for
- [x] tests (tape)
- [x] coverage (istanbul)
- [x] linter (prettier)

Ref: https://github.com/dwyl/learn-pre-commit

**Comment by SimonLab** [comment]
For the prettier pre-commit: https://prettier.io/docs/en/precommit.html
ref: https://github.com/charterindex/application/issues/4#issuecomment-375015245

**Comment by SimonLab** [comment]
To add a pre-commit coverage:
- add a new command in package.json:
```
"coverage":
      "istanbul cover tape ./test/*.test.js && istanbul check-coverage --statements 100 --functions 100 --lines 100 --branches 50"
```
- include this command on the pre-commit section of the package.json:
```
"pre-commit": ["test-pre-commit", "linter", "coverage"]
```

**Comment by Cleop** [comment]
For the prettier linter add it to the pre-commit list as @SimonLab has illustrated above and also in your scripts as:  `"linter": "pretty-quick --staged"`

And install husky and pretty-quick as dev deps:
"husky": "^0.14.3",
"pretty-quick": "^1.4.1"

See: https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick for more information. We followed option 2.

Also make sure you have `pre-commit` installed as a dev dep.

**Comment by SimonLab** [comment]
Coverage pre-commit:
![image](https://user-images.githubusercontent.com/6057298/37821867-badfcf24-2e7c-11e8-9045-dec817568f44.png)

prettier pre-commit:
![image](https://user-images.githubusercontent.com/6057298/37821882-c7336b32-2e7c-11e8-9c8d-886b9e5130c3.png)

tests pre-commit:
![image](https://user-images.githubusercontent.com/6057298/37821891-d204f30a-2e7c-11e8-9a60-378bf699cf7f.png)
