### ISSUE TITLE
Add front-end tests

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#33]
As a developer I want to add front-end tests
So the application is fully tested

We have already some integration and unit tests implemented with tape.
We can add more tests focusing on the front-end.
- [ ] Select testing tool, nightwatch, nightmare,..? https://github.com/dwyl/learn-nightwatch https://github.com/dwyl/learn-daydream-and-nightmare any other tools?
- [ ] Setup a simple test and make sure it can be run with CircleCi

**Comment by SimonLab** [comment]
I'm going to have a look at adding nightmare: https://github.com/segmentio/nightmare and write a test with tape.

**Comment by nelsonic** [comment]
@SimonLab please _consider_ using https://www.cypress.io
We haven't written our "tutorial" for it, yet ... https://github.com/dwyl/learn-cypress.io
but we have been using it on a couple of projects (_ask @Danwhy & @shouston3 ..._)
and it's _much_ faster than anything `else` we've used in the past.

**Comment by SimonLab** [comment]
Thanks for the link for cypress, I'm going to have a look at it now :+1:

**Comment by SimonLab** [comment]
cypress documentation: https://docs.cypress.io/guides/overview/why-cypress.html#
- ```npm install cypress --save-dev```
- run ```./node_modules/cypress/bin/cypress open``` This will create new folders and an example test
- add test in cypress/integration folder

**Comment by SimonLab** [comment]
Run cypress tests with CircleCi: https://github.com/cypress-io/cypress-example-docker-circle

**Comment by SimonLab** [comment]
Cypress is not running on CircleCi:
![image](https://user-images.githubusercontent.com/6057298/37905343-7317820a-30f6-11e8-8c01-f057c5245989.png)

I've added cypress test on the npm test command: https://github.com/charterindex/application/blob/11126873224370e1e9e51f4f958cc5c9d8f45aef/package.json#L9

But I might need to add it directly to the CircleCi config:
![image](https://user-images.githubusercontent.com/6057298/37902974-23d45dec-30ee-11e8-82dd-f924d9a47ab7.png)

**Comment by SimonLab** [comment]
The server needs to be started on CircleCi before Cypress tests can be tested.
We need to tell CircleCi to wait while the server is not ready.
Can we use a command similar to:
```
      - |
    until $(curl --output /dev/null --silent --fail http://localhost:4001);do
      printf '.'
      sleep 5
    done
```

**Comment by SimonLab** [comment]
The server start (need to check the port is 4000) but the process block the rest of the tests to run:
![image](https://user-images.githubusercontent.com/6057298/37909898-18587906-3104-11e8-9045-f325a9d56b4a.png)

So I need to start the server in a background process: https://circleci.com/docs/1.0/background-process/

**Comment by SimonLab** [comment]
I manage to start the server in the background and wait for it to be ready (sleep 10). However it seems that CircleCi is still missing some dependencies:
![image](https://user-images.githubusercontent.com/6057298/37911770-e377b67a-3108-11e8-82c0-cd72ce028b33.png)

**Comment by SimonLab** [comment]
Changing the docker image to use the Cypress one allow us to run Cypress. However the server is not available on localhost:
![image](https://user-images.githubusercontent.com/6057298/37913045-db6edc3a-310b-11e8-9d21-0e3e33529a20.png)
It might be because CircleCi use https instead?

**Comment by SimonLab** [comment]
Instead of changing the value of the baseUrl in Cypress which is different from dev/staging/test and different on other developers machine, I've added th PORT environment variable to CircleCI to 4000 et voila:
![image](https://user-images.githubusercontent.com/6057298/37914797-fc6ca3dc-310f-11e8-987b-de72241f87a5.png)

**Comment by nelsonic** [comment]
@SimonLab looks like it's working. 👍
