### ISSUE TITLE
Replace `request` by `superagent`

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#34]
see https://github.com/charterindex/application/pull/30#discussion_r176509426

https://github.com/visionmedia/superagent is another way to send request to the API

- [ ] ~How to mock request with superagent~
- [x] Implement request function with superagent

The endpoint to get yacht has been simplify and we don't need mocks at this stage

**Comment by nelsonic** [comment]
Done. (_thanks @SimonLab_ 🎉 )
