### ISSUE TITLE
Codecov report not display on PR

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#38]
My last 2 PRs didn't display the coverage report from Codecov.
However
- it seems that CircleCi is running the test and upload the report:
![image](https://user-images.githubusercontent.com/6057298/37837731-e9c21f64-2ead-11e8-8963-fcfdea73ee4d.png)
- But on the PRs tab on Codecov the report seems to not be uploaded:
![image](https://user-images.githubusercontent.com/6057298/37837772-0a5a42e2-2eae-11e8-8f63-439083dac46f.png)

I'm not sure if the problem is directly linked to Codecov or if we change some configuration (or need to add some?)
@Cleop do you have the same issue with your PRs?

**Comment by Cleop** [comment]
My PR also doesn't feature Codecov:
https://github.com/charterindex/application/pull/39#issue-177128291

**Comment by iteles** [comment]
@shouston3 We heard you guys saw this happen today in TC, did you come to a solution for it?

**Comment by shouston3** [comment]
Ours problem was a different problem.

Our problem arose from our repository being private and needing to supply an additional token.

Yours seems trickier to fix as it was working before, then has stopped without apparent config change (according to @SimonLab). I don't know why this might be, sorry.

I would suggest pushing up a branch identical to when it was a working state and see if codecov functions.

If it doesn't then it seems like it's perhaps an issue with some configuration done on the codecov site.

**Comment by SimonLab** [comment]
CodeCov report is back on this PR: https://github.com/charterindex/application/pull/40
Which makes me think that it was a delay on Codecov part when display the report. Let's keep this issue open to test on the next few PRs

**Comment by SimonLab** [comment]
We didn't have any other issue with codecov, closing for now.
