### ISSUE TITLE
Add 'prettier' linter

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#4]
As a developer
I want to code to follow standard conventions
So that I can read others code easily and collaborate effectively with others

- [x] Add 'prettier' linter:
https://www.npmjs.com/package/prettier - `npm install prettier`

Question, do we want to add 'pretty' for html consistency?
https://www.npmjs.com/package/pretty  - `npm install pretty`

**Comment by SimonLab** [comment]
@Cleop I don't think `pretty` is necessary. From the doc it seems that it display/indent an html string in a specific way:
![image](https://user-images.githubusercontent.com/6057298/37701238-1e334350-2ce6-11e8-8022-4ea0186fe3ad.png)

I think we will use a template engine (ex: Handlebars) and I'm wondering if this tool will keep working with this specific syntax.

I think Prettier might also be able to do this.

**Comment by SimonLab** [comment]
- [ ] install prettier on Atom: https://github.com/prettier/prettier-atom
Prettier can also be use on other editors:
![image](https://user-images.githubusercontent.com/6057298/37701491-1e32ed00-2ce7-11e8-8141-ca73ef43ff90.png)
- [ ] Install prettier with npm: ```npm install --save-dev prettier``` and add it to a pre-commit hook, see https://prettier.io/docs/en/precommit.html
- [ ] use prettier with the Continuous Integration tool (see #6 )

**Comment by Cleop** [comment]
I went with option 2, installing 'pretty-quick' for the pre-commit hook as it is: 'Great for when you want an entire file formatting on your changed/staged files.'

**Comment by Cleop** [comment]
Closing as now complete and `technical` so can't be tested.
