### ISSUE TITLE
Tachyons not working with media query classes

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#47]
Trying to work on #22 it became apparent that Tachyons classes were not working properly when they involved a media query. 

Upon investigation it appears that we are missing a couple of postcss plugins to make them render properly. We were missing:

- `postcss-custom-media`
- `postcss-custom-properties`

- [x] Add these two dev dependencies 
- [x] Add them to the postcss config file

**Comment by nelsonic** [comment]
fixed. 👍
