### ISSUE TITLE
Do CI have a test account/ email for testing and setting up accounts?

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#5]
As a developer
I want to know the details for test users and creating new accounts
So that I can test the product easily and set up new accounts on other services where necessary

Do CI have a dev/test email address that we can use and create accounts etc with? This is with regards to testing the API and also for setting up new accounts for services such as Google Analytics/ Heroku etc.

**Comment by SimonLab** [comment]
On our previous projects we have created a dedicated email address that we use for signup to the necessary tools (Heroku, Analytics, S3...).
We share the credentials of this email address like this the tools can be transfered later on if necessary to other accounts.
With a specific email address we won't have also to access any other credentials and private information from another email account.
@Cleop I think we could create this account and share the credentials with @PeterTrotter , do you agree?

**Comment by Cleop** [comment]
Cool, I've set up: ` charter.index.dev@gmail.com` as charter.index was taken.

**Comment by Cleop** [comment]
We now have the details for the API don't we @SimonLab? So can this issue now be closed?

**Comment by SimonLab** [comment]
@Cleop yes I think this issue can be closed now. We will need to share the credentials and confirm that people can access them but otherwise it looks good to me now
