### ISSUE TITLE
Update yacht API query

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#50]
As a developer I want to query the most recent version of the CI API
So that I can get the latest version of data:

The api can now be query on `/api/yachts/:idYacht` instead of `/yachts/fleet/:idYacht`
- [x] change the endpoint which display the name of a yacht: 
https://github.com/charterindex/application/blob/79aebccfb31560c804bf224c49224a1be15e6e2b/routes/yacht.js#L7
- [x] Update tests if some yacht tests are broken (the api is in progress so some id might not work anymore)

**Comment by SimonLab** [comment]
The name of the yacht is now stored in `attributes.name`

**Comment by nelsonic** [comment]
merged. 👍
