### ISSUE TITLE
Test CI API with Cypress

### ISSUE THREAD

**Issue by SimonLab** [charterindex/application#54]
As a developer I want to test the CI API directly
So that I can detect any changes occuring on the API

- [x] Setup new test file with Cypress to test the `/api/yachts/:idYacht` endpoint
- [x] Load environment variables for Cypress (user/password for api requests)
- [x] Test content type is json and the main data are returned (id, name, attributes,...)

**Comment by SimonLab** [comment]
To test the api, we can use `cy.request`:
```

    const getYacht = (id) => {
      var url = Cypress.env('API_ROOT_URL') + '/yachts/' + id;
      return cy.request({
        url: url,
        auth: {
          username: Cypress.env('API_USER'),
          password: Cypress.env('API_PASSWORD')
        }
      })
      .its('body')
    }
```
However the body is not parse to json and we can't test the properties of the response.
I think this is due to the content type returned which is `application/vnd.api+json`
I've tested with another API where the content type is `application/json` and managed to get values of the json response.
So we need to find a way to parse the response via Cypress before being able to test the json object

**Comment by SimonLab** [comment]
A solution is to parse the body manually:
```
    getYacht('2168')
    .then((response) => {
      var body = JSON.parse(response.body)
      expect(body.data.attributes).to.have.property('name', 'AD ASTRA')
    })
```
However it would have been nice if Cypress could parse the body automatically

**Comment by iteles** [comment]
👍 Initial tests implemented, now we add them throughout as required.
