### ISSUE TITLE
Research and implement CI

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#6]
Investigate CI to try and find an option that allows one free closed source application. Previously we've used Circle CI but we need to check the costings of this.

- [x] Set up the agreed CI

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/37699196-4476bd88-2cde-11e8-9afc-2f371d3892e1.png)

To learn a bit more about Continuous Integration and to read about what Travis and Circle CI offer:
- https://github.com/dwyl/learn-circleci
- https://github.com/dwyl/learn-travis
- https://en.wikipedia.org/wiki/Continuous_integration
- https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5
 
Here are the main points with the 3 CI tools have used previously:

## [Travis](https://travis-ci.org/)

- Free for public Github repositories
- [Travis Pro](https://docs.travis-ci.com/user/travis-pro/) necessary for private repositories. A trial period include 100 free builds.
see the different [Travis Plans](https://travis-ci.com/plans)

## [Circle CI](https://circleci.com/)
- Free plan for public and private Github repositories
- Pay plans for build speed: https://circleci.com/pricing/

## [CodeShip](https://documentation.codeship.com/)
I couldn't find inforamation about prices for public/private repos specifically but from their pricing page it looks like the price is based on the number of builds:
![image](https://user-images.githubusercontent.com/6057298/37699783-ddc050ce-2ce0-11e8-9744-2f108a0d01f5.png)

- https://codeship.com/pricing

All of the tools are on the Github marketplace: https://github.com/marketplace/category/continuous-integration and they can easily be integreted with Heroku

Travis is easy to integate with public repositories and it's the one I've mostly use, however depending on the access of this repo I think I would give a go with CircleCi. @Cleop @nelsonic @iteles do you agree with this choice?

**Comment by Cleop** [comment]
I think CircleCI looks best if this repo is private 👍 Otherwise Travis is good.

**Comment by iteles** [comment]
CircleCI is still the best option. Thanks for checking the evolution @SimonLab .

**Comment by SimonLab** [comment]
The documentation to initialise CircleCi can be found here: https://circleci.com/docs/2.0/
The main steps of the documenation are well explained but here are the main two steps we had to do to trigger a build:
- creating a config file for CircleCi in .circleci/config.yml
- update the config file and make sure the command to run the tests are correct. In our case we are using `npm` instead of `yarn` and the command for the test (which can be found in the package.json) is `npm test`

**Comment by Cleop** [comment]
Closing as now complete and `technical` so can't be tested.
